README.md

Updated the readme file. 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

SCIM2-Connector-Readme updated

---

README.md
scim2/Ballerina.md
scim2/scim2_connector.bal
scim2/scim2_connector_utils.bal
scim2/scim2_endpoint.bal
scim2/scim2_records.bal
scim2/tests/README.md
scim2/tests/test.bal

Fixed some naming issues and bugs

---

Ballerina.toml
README.md
scim2/Package.md
scim2/scim2_connector.bal
scim2/scim2_endpoint.bal
scim2/scim2_records.bal
scim2/tests/README.md
scim2/tests/test.bal

Included the secure client and refactored to latest ballerina version

---

.gitignore
Ballerina.toml
README.md
ballerina.conf
scim2/Package.md
scim2/scim2_endpoint.bal
scim2/scim2_utils.bal
scim2/tests/README.md
scim2/tests/test.bal

edited indentations in .md files

---

Ballerina.toml
README.md
scim2/Package.md
scim2/scim2_connector.bal
scim2/scim2_data_mapping.bal
scim2/scim2_endpoint.bal
scim2/tests/README.md
scim2/tests/test.bal

Refactored to beta3, Restructured Package.md

---

Ballerina.toml
README.md
scim2/Package.md
scim2/scim2_connector.bal
scim2/tests/README.md
scim2/tests/test.bal

Refactored to beta10 syntax

---

Ballerina.toml
scim2/scim2_connector.bal
scim2/scim2_types.bal

Fixed Annotations

---

README.md
scim2/scim2_connector.bal
scim2/scim2_utils.bal
scim2/tests/README.md

Fix for beta15 changes

---

README.md
scim2/Package.md
scim2/scim2_endpoint.bal
scim2/tests/test.bal

Remove redundancy

---

Ballerina.toml
scim2/Package.md

Update package overview 

---

.gitignore
Ballerina.toml
README.md
scim2/Package.md
scim2/tests/README.md

Update md files

---

Ballerina.toml

Update toml file

---

README.md
scim2/Package.md

Update markdown files

---

Ballerina.toml
README.md
scim2/Package.md
scim2/scim2_connector.bal
scim2/scim2_endpoint.bal
scim2/scim2_types.bal
scim2/tests/README.md

- Fix syntax issues
- Update markdown files and toml file for 0.980.0 release

Prepare connector for Ballerina 0.980.0 release

---

Ballerina.toml
README.md
scim2/Package.md
scim2/scim2_connector.bal
scim2/scim2_constants.bal
scim2/scim2_endpoint.bal
scim2/scim2_types.bal
scim2/scim2_utils.bal
scim2/tests/README.md

Fix connector with latest ballerina changes.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Fix connector with latest ballerina changes

---

.travis.yml
Ballerina.toml
README.md
scim2/Module.md
scim2/scim2_connector.bal
scim2/tests/README.md

Sync with ballerina 0.983.0
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Sync with ballerina 0.983.0

---

scim2/scim2_endpoint.bal

Made the changes in the endpoint file

---

Ballerina.toml
README.md
scim2/Module.md
scim2/scim2_endpoint.bal

- Fix a bug in remote functions
- Fix markdown and update toml version

Release for Ballerina 0.990.0 RC3

---

Ballerina.toml
README.md
scim2/Module.md
scim2/scim2_endpoint.bal
scim2/tests/README.md
scim2/tests/test.bal

Fix connector for Ballerina 0.990.3

---

Ballerina.toml
README.md
scim2/Module.md

Fix code samples in the README.md

---

README.md

Fix issue in the readme file

---

.travis.yml

> Update the .travis file to ballerina 1.0.0

Update travis file to build with ballerina 1.0.0
